---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: genesis
  namespace: local
  labels:
    app.kubernetes.io/name: genesis
    app.kubernetes.io/component: node
    app.kubernetes.io/part-of: elesto
spec:
  replicas: 1
  serviceName: genesis
  selector:
    matchLabels:
      app.kubernetes.io/name: genesis
      app.kubernetes.io/component: node
      app.kubernetes.io/part-of: elesto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: genesis
        app.kubernetes.io/component: node
        app.kubernetes.io/part-of: elesto
    spec:
      initContainers:
        - name: init-blockchain
          image: elestod-init:local
          command:
            - init-genesis.sh
          env:
            - name: CHAIN_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MONIKER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - secretRef:
                name: genesis-accounts
          #securityContext: # TODO not working
          #  runAsUser: 20000
          #  runAsGroup: 20000
          #  runAsNonRoot: true
          volumeMounts:
            - name: node-home
              mountPath: /home/
      containers:
        - name: application
          image: us-central1-docker.pkg.dev/elesto/elesto/elestod:2.0.0-rc2-snapshots
          args: [
            "start",
            "--db_backend", "goleveldb",
            "--grpc.enable", "true",
            "--grpc-web.enable", "false",
            "--moniker", "$(MONIKER)",
            "--home", "/home/",
            "--log_level", "info",
            "--pruning", "default",
            "--rpc.laddr", "tcp://0.0.0.0:26657",
            "--state-sync.snapshot-interval", "100",
            "--state-sync.snapshot-keep-recent", "2"
          ]
          env:
            - name: MONIKER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources: { }
          ports:
            - name: api
              containerPort: 1317
            - name: grpc
              containerPort: 9090
            - name: grpc-web
              containerPort: 9091
            - name: abci
              containerPort: 26658
            - name: rpc
              containerPort: 26657
            - name: p2p
              containerPort: 26656
            - name: telemetry
              containerPort: 26660
            - name: pprof
              containerPort: 6060
          livenessProbe:
            httpGet:
              port: rpc
              path: /health
          readinessProbe:
            exec:
              command:
                - /tendermint-readiness
          volumeMounts:
            - name: node-home
              mountPath: /home/
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: blockchain-node
  volumeClaimTemplates:
    - metadata:
        name: node-home
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
