---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blockchain-node
  namespace: local
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: blockchain-node
  namespace: local
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "list", "get", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "secrets" ]
    verbs: [ "get", "create", "update", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blockchain-node
  namespace: local
subjects:
  - kind: ServiceAccount
    name: blockchain-node
roleRef:
  kind: Role
  name: blockchain-node
  apiGroup: rbac.authorization.k8s.io
