// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: credential/v1/tx.proto

package credential

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgPublishCredentialDefinitionRequest struct {
	CredentialDefinition *CredentialDefinition `protobuf:"bytes,1,opt,name=credentialDefinition,proto3" json:"credentialDefinition,omitempty"`
	Signer               string                `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgPublishCredentialDefinitionRequest) Reset()         { *m = MsgPublishCredentialDefinitionRequest{} }
func (m *MsgPublishCredentialDefinitionRequest) String() string { return proto.CompactTextString(m) }
func (*MsgPublishCredentialDefinitionRequest) ProtoMessage()    {}
func (*MsgPublishCredentialDefinitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c566edfa2a610e60, []int{0}
}
func (m *MsgPublishCredentialDefinitionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPublishCredentialDefinitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPublishCredentialDefinitionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPublishCredentialDefinitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPublishCredentialDefinitionRequest.Merge(m, src)
}
func (m *MsgPublishCredentialDefinitionRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgPublishCredentialDefinitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPublishCredentialDefinitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPublishCredentialDefinitionRequest proto.InternalMessageInfo

type MsgPublishCredentialDefinitionResponse struct {
}

func (m *MsgPublishCredentialDefinitionResponse) Reset() {
	*m = MsgPublishCredentialDefinitionResponse{}
}
func (m *MsgPublishCredentialDefinitionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPublishCredentialDefinitionResponse) ProtoMessage()    {}
func (*MsgPublishCredentialDefinitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c566edfa2a610e60, []int{1}
}
func (m *MsgPublishCredentialDefinitionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPublishCredentialDefinitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPublishCredentialDefinitionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPublishCredentialDefinitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPublishCredentialDefinitionResponse.Merge(m, src)
}
func (m *MsgPublishCredentialDefinitionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPublishCredentialDefinitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPublishCredentialDefinitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPublishCredentialDefinitionResponse proto.InternalMessageInfo

type MsgUpdateCredentialDefinitionRequest struct {
	CredentialDefinitionID string `protobuf:"bytes,1,opt,name=credentialDefinitionID,proto3" json:"credentialDefinitionID,omitempty"`
	Active                 bool   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	SupersededBy           string `protobuf:"bytes,3,opt,name=supersededBy,proto3" json:"supersededBy,omitempty"`
	Signer                 string `protobuf:"bytes,4,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgUpdateCredentialDefinitionRequest) Reset()         { *m = MsgUpdateCredentialDefinitionRequest{} }
func (m *MsgUpdateCredentialDefinitionRequest) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCredentialDefinitionRequest) ProtoMessage()    {}
func (*MsgUpdateCredentialDefinitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c566edfa2a610e60, []int{2}
}
func (m *MsgUpdateCredentialDefinitionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCredentialDefinitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCredentialDefinitionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCredentialDefinitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCredentialDefinitionRequest.Merge(m, src)
}
func (m *MsgUpdateCredentialDefinitionRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCredentialDefinitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCredentialDefinitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCredentialDefinitionRequest proto.InternalMessageInfo

type MsgUpdateCredentialDefinitionResponse struct {
}

func (m *MsgUpdateCredentialDefinitionResponse) Reset()         { *m = MsgUpdateCredentialDefinitionResponse{} }
func (m *MsgUpdateCredentialDefinitionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCredentialDefinitionResponse) ProtoMessage()    {}
func (*MsgUpdateCredentialDefinitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c566edfa2a610e60, []int{3}
}
func (m *MsgUpdateCredentialDefinitionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCredentialDefinitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCredentialDefinitionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCredentialDefinitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCredentialDefinitionResponse.Merge(m, src)
}
func (m *MsgUpdateCredentialDefinitionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCredentialDefinitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCredentialDefinitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCredentialDefinitionResponse proto.InternalMessageInfo

type MsgIssuePublicVerifiableCredentialRequest struct {
	Credential             *PublicVerifiableCredential `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	CredentialDefinitionID string                      `protobuf:"bytes,2,opt,name=credentialDefinitionID,proto3" json:"credentialDefinitionID,omitempty"`
	Signer                 string                      `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgIssuePublicVerifiableCredentialRequest) Reset() {
	*m = MsgIssuePublicVerifiableCredentialRequest{}
}
func (m *MsgIssuePublicVerifiableCredentialRequest) String() string {
	return proto.CompactTextString(m)
}
func (*MsgIssuePublicVerifiableCredentialRequest) ProtoMessage() {}
func (*MsgIssuePublicVerifiableCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c566edfa2a610e60, []int{4}
}
func (m *MsgIssuePublicVerifiableCredentialRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIssuePublicVerifiableCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIssuePublicVerifiableCredentialRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIssuePublicVerifiableCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIssuePublicVerifiableCredentialRequest.Merge(m, src)
}
func (m *MsgIssuePublicVerifiableCredentialRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgIssuePublicVerifiableCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIssuePublicVerifiableCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIssuePublicVerifiableCredentialRequest proto.InternalMessageInfo

type MsgIssuePublicVerifiableCredentialResponse struct {
}

func (m *MsgIssuePublicVerifiableCredentialResponse) Reset() {
	*m = MsgIssuePublicVerifiableCredentialResponse{}
}
func (m *MsgIssuePublicVerifiableCredentialResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgIssuePublicVerifiableCredentialResponse) ProtoMessage() {}
func (*MsgIssuePublicVerifiableCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c566edfa2a610e60, []int{5}
}
func (m *MsgIssuePublicVerifiableCredentialResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIssuePublicVerifiableCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIssuePublicVerifiableCredentialResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIssuePublicVerifiableCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIssuePublicVerifiableCredentialResponse.Merge(m, src)
}
func (m *MsgIssuePublicVerifiableCredentialResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgIssuePublicVerifiableCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIssuePublicVerifiableCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIssuePublicVerifiableCredentialResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgPublishCredentialDefinitionRequest)(nil), "elestodao.elesto.credential.v1.MsgPublishCredentialDefinitionRequest")
	proto.RegisterType((*MsgPublishCredentialDefinitionResponse)(nil), "elestodao.elesto.credential.v1.MsgPublishCredentialDefinitionResponse")
	proto.RegisterType((*MsgUpdateCredentialDefinitionRequest)(nil), "elestodao.elesto.credential.v1.MsgUpdateCredentialDefinitionRequest")
	proto.RegisterType((*MsgUpdateCredentialDefinitionResponse)(nil), "elestodao.elesto.credential.v1.MsgUpdateCredentialDefinitionResponse")
	proto.RegisterType((*MsgIssuePublicVerifiableCredentialRequest)(nil), "elestodao.elesto.credential.v1.MsgIssuePublicVerifiableCredentialRequest")
	proto.RegisterType((*MsgIssuePublicVerifiableCredentialResponse)(nil), "elestodao.elesto.credential.v1.MsgIssuePublicVerifiableCredentialResponse")
}

func init() { proto.RegisterFile("credential/v1/tx.proto", fileDescriptor_c566edfa2a610e60) }

var fileDescriptor_c566edfa2a610e60 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2e, 0x4a, 0x4d,
	0x49, 0xcd, 0x2b, 0xc9, 0x4c, 0xcc, 0xd1, 0x2f, 0x33, 0xd4, 0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x92, 0x4b, 0xcd, 0x49, 0x2d, 0x2e, 0xc9, 0x4f, 0x49, 0xcc, 0xd7, 0x83, 0xb0,
	0xf4, 0x10, 0x0a, 0xf5, 0xca, 0x0c, 0xa5, 0x44, 0xd2, 0xf3, 0xd3, 0xf3, 0xc1, 0x4a, 0xf5, 0x41,
	0x2c, 0x88, 0x2e, 0x29, 0x39, 0x54, 0xd3, 0x90, 0xb4, 0x80, 0xe5, 0x95, 0x36, 0x33, 0x72, 0xa9,
	0xfa, 0x16, 0xa7, 0x07, 0x94, 0x26, 0xe5, 0x64, 0x16, 0x67, 0x38, 0xc3, 0xa5, 0x5d, 0x52, 0xd3,
	0x32, 0xf3, 0x32, 0x4b, 0x32, 0xf3, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x32,
	0xb8, 0x44, 0x92, 0xb1, 0x48, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x99, 0xe8, 0xe1, 0x77,
	0x9e, 0x1e, 0x56, 0xa3, 0xb1, 0x9a, 0x28, 0x24, 0xc6, 0xc5, 0x56, 0x9c, 0x99, 0x9e, 0x97, 0x5a,
	0x24, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe5, 0x59, 0x71, 0x74, 0x2c, 0x90, 0x67, 0x78,
	0xb1, 0x40, 0x9e, 0x41, 0x49, 0x83, 0x4b, 0x8d, 0x90, 0xa3, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53,
	0x95, 0xf6, 0x30, 0x72, 0xa9, 0xf8, 0x16, 0xa7, 0x87, 0x16, 0xa4, 0x24, 0x96, 0xa4, 0xe2, 0xf3,
	0x9e, 0x19, 0x72, 0xc0, 0x23, 0xa4, 0x3d, 0x5d, 0xc0, 0x1e, 0xe4, 0x0c, 0xc2, 0x21, 0x0b, 0x72,
	0x6c, 0x62, 0x72, 0x49, 0x66, 0x59, 0x2a, 0xd8, 0xb1, 0x1c, 0x41, 0x50, 0x9e, 0x90, 0x12, 0x17,
	0x4f, 0x71, 0x69, 0x41, 0x6a, 0x51, 0x71, 0x6a, 0x4a, 0x6a, 0x8a, 0x53, 0xa5, 0x04, 0x33, 0xd8,
	0x14, 0x14, 0x31, 0x24, 0x8f, 0xb2, 0xe0, 0xf0, 0xa8, 0x3a, 0x38, 0x76, 0xf0, 0xb9, 0x1e, 0xea,
	0xcf, 0x87, 0x8c, 0x5c, 0x9a, 0xbe, 0xc5, 0xe9, 0x9e, 0xc5, 0xc5, 0xa5, 0xa9, 0xe0, 0x70, 0x49,
	0x0e, 0x4b, 0x2d, 0xca, 0x4c, 0xcb, 0x4c, 0x4c, 0xca, 0x41, 0xd2, 0x08, 0xf3, 0x6c, 0x14, 0x17,
	0x17, 0xc2, 0x3b, 0xd0, 0x18, 0xb4, 0x22, 0x14, 0x83, 0x78, 0x8c, 0x45, 0x32, 0x0d, 0x4f, 0x40,
	0x32, 0x11, 0x0a, 0x48, 0x68, 0x60, 0x30, 0xe3, 0x08, 0x0c, 0x1d, 0x2e, 0x2d, 0x62, 0xbc, 0x08,
	0x09, 0x11, 0xa3, 0xd9, 0x2c, 0x5c, 0xcc, 0xbe, 0xc5, 0xe9, 0x42, 0x6b, 0x18, 0xb9, 0xa4, 0xf1,
	0xa4, 0x14, 0x21, 0x57, 0x42, 0xfe, 0x26, 0x2a, 0x7b, 0x48, 0xb9, 0x51, 0x6a, 0x0c, 0xc4, 0xd9,
	0x42, 0x2b, 0x19, 0xb9, 0xa4, 0x70, 0xc7, 0xb7, 0x90, 0x0b, 0x11, 0xd6, 0x10, 0x4c, 0xec, 0x52,
	0xae, 0x14, 0x9a, 0x02, 0x75, 0xeb, 0x0e, 0x46, 0x2e, 0x79, 0x02, 0xd1, 0x21, 0xe4, 0x49, 0x84,
	0x55, 0xc4, 0xa5, 0x5a, 0x29, 0x2f, 0x6a, 0x18, 0x05, 0x71, 0xba, 0x93, 0xdb, 0x89, 0x47, 0x72,
	0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7,
	0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0xe9, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25,
	0xe7, 0xe7, 0xea, 0x43, 0x6c, 0xd1, 0x4d, 0x49, 0xcc, 0x87, 0x32, 0xf5, 0xcb, 0x4c, 0xf4, 0x2b,
	0x90, 0x4a, 0xd1, 0x24, 0x36, 0x70, 0x31, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x55, 0x9d,
	0xe6, 0x70, 0xb6, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	PublishCredentialDefinition(ctx context.Context, in *MsgPublishCredentialDefinitionRequest, opts ...grpc.CallOption) (*MsgPublishCredentialDefinitionResponse, error)
	UpdateCredentialDefinition(ctx context.Context, in *MsgUpdateCredentialDefinitionRequest, opts ...grpc.CallOption) (*MsgUpdateCredentialDefinitionResponse, error)
	IssuePublicVerifiableCredential(ctx context.Context, in *MsgIssuePublicVerifiableCredentialRequest, opts ...grpc.CallOption) (*MsgIssuePublicVerifiableCredentialResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) PublishCredentialDefinition(ctx context.Context, in *MsgPublishCredentialDefinitionRequest, opts ...grpc.CallOption) (*MsgPublishCredentialDefinitionResponse, error) {
	out := new(MsgPublishCredentialDefinitionResponse)
	err := c.cc.Invoke(ctx, "/elestodao.elesto.credential.v1.Msg/PublishCredentialDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCredentialDefinition(ctx context.Context, in *MsgUpdateCredentialDefinitionRequest, opts ...grpc.CallOption) (*MsgUpdateCredentialDefinitionResponse, error) {
	out := new(MsgUpdateCredentialDefinitionResponse)
	err := c.cc.Invoke(ctx, "/elestodao.elesto.credential.v1.Msg/UpdateCredentialDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) IssuePublicVerifiableCredential(ctx context.Context, in *MsgIssuePublicVerifiableCredentialRequest, opts ...grpc.CallOption) (*MsgIssuePublicVerifiableCredentialResponse, error) {
	out := new(MsgIssuePublicVerifiableCredentialResponse)
	err := c.cc.Invoke(ctx, "/elestodao.elesto.credential.v1.Msg/IssuePublicVerifiableCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	PublishCredentialDefinition(context.Context, *MsgPublishCredentialDefinitionRequest) (*MsgPublishCredentialDefinitionResponse, error)
	UpdateCredentialDefinition(context.Context, *MsgUpdateCredentialDefinitionRequest) (*MsgUpdateCredentialDefinitionResponse, error)
	IssuePublicVerifiableCredential(context.Context, *MsgIssuePublicVerifiableCredentialRequest) (*MsgIssuePublicVerifiableCredentialResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) PublishCredentialDefinition(ctx context.Context, req *MsgPublishCredentialDefinitionRequest) (*MsgPublishCredentialDefinitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishCredentialDefinition not implemented")
}
func (*UnimplementedMsgServer) UpdateCredentialDefinition(ctx context.Context, req *MsgUpdateCredentialDefinitionRequest) (*MsgUpdateCredentialDefinitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCredentialDefinition not implemented")
}
func (*UnimplementedMsgServer) IssuePublicVerifiableCredential(ctx context.Context, req *MsgIssuePublicVerifiableCredentialRequest) (*MsgIssuePublicVerifiableCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssuePublicVerifiableCredential not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_PublishCredentialDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPublishCredentialDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PublishCredentialDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elestodao.elesto.credential.v1.Msg/PublishCredentialDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PublishCredentialDefinition(ctx, req.(*MsgPublishCredentialDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCredentialDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCredentialDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCredentialDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elestodao.elesto.credential.v1.Msg/UpdateCredentialDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCredentialDefinition(ctx, req.(*MsgUpdateCredentialDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_IssuePublicVerifiableCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgIssuePublicVerifiableCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).IssuePublicVerifiableCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elestodao.elesto.credential.v1.Msg/IssuePublicVerifiableCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).IssuePublicVerifiableCredential(ctx, req.(*MsgIssuePublicVerifiableCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "elestodao.elesto.credential.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishCredentialDefinition",
			Handler:    _Msg_PublishCredentialDefinition_Handler,
		},
		{
			MethodName: "UpdateCredentialDefinition",
			Handler:    _Msg_UpdateCredentialDefinition_Handler,
		},
		{
			MethodName: "IssuePublicVerifiableCredential",
			Handler:    _Msg_IssuePublicVerifiableCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "credential/v1/tx.proto",
}

func (m *MsgPublishCredentialDefinitionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPublishCredentialDefinitionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPublishCredentialDefinitionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x12
	}
	if m.CredentialDefinition != nil {
		{
			size, err := m.CredentialDefinition.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPublishCredentialDefinitionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPublishCredentialDefinitionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPublishCredentialDefinitionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCredentialDefinitionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCredentialDefinitionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCredentialDefinitionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SupersededBy) > 0 {
		i -= len(m.SupersededBy)
		copy(dAtA[i:], m.SupersededBy)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SupersededBy)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.CredentialDefinitionID) > 0 {
		i -= len(m.CredentialDefinitionID)
		copy(dAtA[i:], m.CredentialDefinitionID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CredentialDefinitionID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCredentialDefinitionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCredentialDefinitionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCredentialDefinitionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgIssuePublicVerifiableCredentialRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIssuePublicVerifiableCredentialRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIssuePublicVerifiableCredentialRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CredentialDefinitionID) > 0 {
		i -= len(m.CredentialDefinitionID)
		copy(dAtA[i:], m.CredentialDefinitionID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CredentialDefinitionID)))
		i--
		dAtA[i] = 0x12
	}
	if m.Credential != nil {
		{
			size, err := m.Credential.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgIssuePublicVerifiableCredentialResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIssuePublicVerifiableCredentialResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIssuePublicVerifiableCredentialResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgPublishCredentialDefinitionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CredentialDefinition != nil {
		l = m.CredentialDefinition.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgPublishCredentialDefinitionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateCredentialDefinitionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CredentialDefinitionID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Active {
		n += 2
	}
	l = len(m.SupersededBy)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateCredentialDefinitionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgIssuePublicVerifiableCredentialRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Credential != nil {
		l = m.Credential.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CredentialDefinitionID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgIssuePublicVerifiableCredentialResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgPublishCredentialDefinitionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPublishCredentialDefinitionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPublishCredentialDefinitionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialDefinition", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CredentialDefinition == nil {
				m.CredentialDefinition = &CredentialDefinition{}
			}
			if err := m.CredentialDefinition.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPublishCredentialDefinitionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPublishCredentialDefinitionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPublishCredentialDefinitionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCredentialDefinitionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCredentialDefinitionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCredentialDefinitionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialDefinitionID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialDefinitionID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupersededBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupersededBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCredentialDefinitionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCredentialDefinitionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCredentialDefinitionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIssuePublicVerifiableCredentialRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIssuePublicVerifiableCredentialRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIssuePublicVerifiableCredentialRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credential", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Credential == nil {
				m.Credential = &PublicVerifiableCredential{}
			}
			if err := m.Credential.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialDefinitionID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialDefinitionID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIssuePublicVerifiableCredentialResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIssuePublicVerifiableCredentialResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIssuePublicVerifiableCredentialResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
