name: Release Container
on: 
  push:
    branches:
      - main
      - k3d-devnet

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Image metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=raw,value={{date 'YY.DDD-X'}}-{{sha}}
      - name: Build and push elestod
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Init Image metadata
        uses: docker/metadata-action@v4
        id: init-meta
        with:
          images: ghcr.io/${{ github.repository }}-init
          tags: type=raw,value={{date 'YY.DDD-X'}}-{{sha}}
      - name: Build and push elestod-init
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./scripts/devnet/kubernetes/0-init/
          tags: ${{ steps.init-meta.outputs.tags }}
          labels: ${{ steps.init-meta.outputs.labels }}
          build-args: ELESTOD_IMAGE_TAG=ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}
